name: build
on:
  push:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - target: "c"
          - target: "s"

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Get version
        id: version
        run: |
          echo "VERSION=$(grep -E 'frp version: [0-9.]+' README.md | grep -oP '[0-9.]+')" >> $GITHUB_OUTPUT

      - name: Build
        uses: ngc7331/actions@docker-build
        with:
          name: frp${{ matrix.target }}
          version: ${{ steps.version.outputs.VERSION }}
          file: ./frp${{ matrix.target }}/Dockerfile
          context: ./frp${{ matrix.target }}
          platforms: linux/amd64,linux/arm64,linux/riscv64
          build_args: |
            FRP_VERSION=${{ steps.version.outputs.VERSION }}
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

