name: build
on:
  push:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - target: "c"
          - target: "s"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Get version
        run: echo "VERSION=$(sed -n -r 's/^FRP_VERSION \?= (.*)/\1/p' Makefile)" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: ./frp${{ matrix.target }}/Dockerfile
          context: frp${{ matrix.target }}
          build-args: |
            FRP_VERSION=${{ env.VERSION }}
          platforms: linux/amd64,linux/arm64,linux/riscv64
          push: true
          tags: |
            ngc7331/frp${{ matrix.target }}:latest
            ngc7331/frp${{ matrix.target }}:${{ env.VERSION }}
            ghcr.io/${{ github.repository }}${{ matrix.target }}:latest
            ghcr.io/${{ github.repository }}${{ matrix.target }}:${{ env.VERSION }}
